# render.yaml
services:
  - type: web
    name: dbwsso-wumis
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
